# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'
services:

  zookeeper:
    image: hyperledger/fabric-zookeeper
    restart: always
    ports:
      - 2181
      - 2888
      - 3888
    volumes:
      - /var/hyperledger/bddtests/volumes/zookeeper:/var/hyperledger/bddtests/volumes/zookeeper
  
  kafka:
     image: hyperledger/fabric-kafka
     environment:
         - KAFKA_LOG_RETENTION_MS=-1
         - KAFKA_MESSAGE_MAX_BYTES=103809024
         - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
         - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
         - KAFKA_DEFAULT_REPLICATION_FACTOR=${KAFKA_DEFAULT_REPLICATION_FACTOR}  
         - KAFKA_MIN_INSYNC_REPLICAS=2

     ports:
         - 9092 
